export const  Recu =  [
    {
        id:1,
        Nom:'Bulletin de paie 27/01/2022',
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : 'Bulletin de paie',
    },
    {
        id:2,
        Nom:'Bulletin de paie 27/01/2022',
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : 'Bulletin de paie',
    },
    {
        id:3,
        Nom:"Note d'information",
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : "Note d'information",
    },
    {
        id:4,
        Nom:"Note d'information",
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : "Note d'information",
    },
    {
        id:5,
        Nom:'Bulletin de paie 27/01/2022',
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : 'Bulletin de paie',
    },
    {
        id:6,
        Nom:'Bulletin de paie 27/01/2022',
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : 'Bulletin de paie',
    },
    {
        id:7,
        Nom:"Note d'information",
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : "Note d'information",
    },
    {
        id:8,
        Nom:"Note d'information",
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : "Note d'information",
    },
    {
        id:9,
        Nom:'Bulletin de paie 27/01/2022',
        Expediteur : 'Rh',
        entreprise : 'entreprise1',
        date: '22/04/22',
        etiquette : 'Bulletin de paie',
    },

];